source_academique/urls.py
# projet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Ajoutez cette ligne
    path('', include('source_polytechnique.urls')),  # Remplacez par le chemin vers vos URL de notes
]


# Ajoutez cette section pour servir les fichiers médias pendant le développement
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source_polytechnique/urls.py
from .views import register,profile,home,ExemViexs,InterroViexs,TpViexs,NoteViexs,login_view,logout_view
from django.urls import path

urlpatterns = [
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('note/',NoteViexs,name='note'),
    path('tp/',TpViexs,name='tp'),
    path('interro/',InterroViexs,name='interro'),
    path('examen/',ExemViexs,name='exam'),
    path('',home,name='accueil'),
    path('profile/', profile, name='profile'),
    path('register/', register, name='register'),
    # ... autres URLs
]

source_polytechnique/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

from django.contrib.auth.models import User

# Définir les promotions
PROMOTION_CHOICES = [
    ('L1', 'Licence 1'),
    ('PREPA', 'Préparatoire'),
]


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    promotion = models.CharField(max_length=100,choices=PROMOTION_CHOICES)  # Par exemple, 'L1' ou 'PREPA'
    first_name = models.CharField(max_length=30, blank=True, null=True)  # Assurez-vous que ces champs existent
    last_name = models.CharField(max_length=30, blank=True, null=True)
    photo = models.ImageField(upload_to='photos/', blank=True, null=True)
    numero_whatsapp = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return self.user.username


class Message(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Cours(models.Model):
    titre = models.CharField(max_length=200)
    description = models.TextField()
    maman = models.FileField(upload_to='cours/', blank=True, null=True)
    promotion = models.CharField(max_length=5, choices=PROMOTION_CHOICES)
    date_ajout = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name = "Cours"
        verbose_name_plural = "Cours"

    def __str__(self):
        return self.titre

class Interro(models.Model):
    titre = models.CharField(max_length=200)
    fichier = models.FileField(upload_to='interros/')
    promotion = models.CharField(max_length=5, choices=PROMOTION_CHOICES)
    date_ajout = models.DateTimeField(auto_now_add=True)
    date_donnee = models.DateField(default=timezone.now)  # Champ pour la date précise où le TP a été donné

    def __str__(self):
        return self.titre

class Examen(models.Model):
    titre = models.CharField(max_length=200)
    fichier = models.FileField(upload_to='examens/')
    promotion = models.CharField(max_length=5, choices=PROMOTION_CHOICES)
    date_ajout = models.DateTimeField(auto_now_add=True)
    date_donnee = models.DateField(default=timezone.now)  # Champ pour la date précise où le TP a été donné

    def __str__(self):
        return self.titre

class TP(models.Model):
    titre = models.CharField(max_length=200)
    fichier = models.FileField(upload_to='tp/')
    promotion = models.CharField(max_length=5, choices=PROMOTION_CHOICES)
    date_ajout = models.DateTimeField(auto_now_add=True)
    date_donnee = models.DateField(default=timezone.now)  # Champ pour la date précise où le TP a été donné

    def __str__(self):
        return self.titre

class Note(models.Model):
    titre = models.CharField(max_length=200)
    fichier = models.FileField(upload_to='notes/')
    promotion = models.CharField(max_length=5, choices=PROMOTION_CHOICES)
    date_ajout = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titre

from django.db.models.signals import post_save
from django.dispatch import receiver

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()









from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

# Create your models here.

source_polytechnique/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email','password1', 'password2']

    
class ProfileForm(forms.ModelForm):
    PROMOTION_CHOICES = [
        ('PREPA', 'Préparation'),
        ('L1', 'Licence 1'),
        # Ajoute d’autres choix ici si nécessaire
    ]
    promotion = forms.ChoiceField(choices=PROMOTION_CHOICES)
    class Meta:
        model = Profile
        fields = [ 'promotion','first_name','last_name','numero_whatsapp','photo']


from django import forms
from django.contrib.auth.forms import AuthenticationForm

class CustomLoginForm(AuthenticationForm):
    # Vous pouvez personnaliser les widgets si besoin
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Numéro de téléphone, nom d\'utilisateur ou e-mail'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Mot de passe'}))

source_polytechnique/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from .models import Cours, Interro, Examen, TP, Note,Profile,Message
# Create your views here.
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm,ProfileForm
from django.contrib.auth import login, authenticate
from .forms import CustomLoginForm
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.contrib import messages

@login_required
def accueil(request):
    """Affiche les cours disponibles par promotion pour les utilisateurs connectés."""
    promotion = request.user.profile.promotion  # Supposons que vous ayez un modèle Profile lié à l'utilisateur
    cours = Cours.objects.filter(promotion=promotion)
    return render(request, 'source_polytechnique/accueil.html', {
        'cours': cours,
        'promotion': promotion,
    })

@login_required
def cours_detail(request, promotion):
    """Affiche les détails des cours pour une promotion spécifique."""
    cours = Cours.objects.filter(promotion=promotion)
    return render(request, 'source_polytechnique/cours_detail.html', {
        'cours': cours,
        'promotion': promotion,
    })


@login_required
def interros(request):
    """Affiche les interros disponibles pour la promotion de l'utilisateur connecté."""
    promotion = request.user.profile.promotion
    interros = Interro.objects.filter(promotion=promotion)
    return render(request, 'interros.html', {
        'interros': interros,
    })


from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import UserRegistrationForm

def register(request):
    """Permet aux utilisateurs de s'inscrire."""
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            username = user_form.cleaned_data.get('username')
            email = user_form.cleaned_data.get('email')
            password = user_form.cleaned_data.get('password1')  # Assurez-vous d'utiliser le bon champ ici

            if User.objects.filter(email=email).exists():
                messages.error(request, "L'adresse email existe déjà dans la base de données.")
                return render(request, 'register.html', {'user_form': user_form})

            # Créez l'utilisateur avec le mot de passe haché
            user = User.objects.create_user(username=username, email=email, password=password)
            user.save()  # Sauvegarder l'utilisateur dans la base de données

            messages.success(request, "Votre compte a été créé avec succès!")
            return redirect('accueil')
    else:
        user_form = UserRegistrationForm()

    return render(request, 'register.html', {'user_form': user_form})

def ExemViexs(request):
    """ Afficher touot les examen si l'utilisateur n'est pas connecter """
    if request.user.is_authenticated:
            profil = Profile.objects.get(user=request.user)
            user_promotion = profil.promotion
            exam = Examen.objects.filter(promotion = user_promotion)
    else:
        exam = None
        return redirect('accueil')
    context = {
        'exam':exam
    }
    return render(request,'exam.html',context)

def InterroViexs(request):
    """ Afficher touot les examen si l'utilisateur n'est pas connecter """
    if request.user.is_authenticated:
            profil = Profile.objects.get(user=request.user)
            user_promotion = profil.promotion
            interros = Interro.objects.filter(promotion = user_promotion)
    else:
        interros = None
        return redirect('accueil')
    context = {
        'interros':interros
    }
    return render(request,'interro.html',context)

def NoteViexs(request):
    """ Afficher touot les examen si l'utilisateur n'est pas connecter """
    if request.user.is_authenticated:
            profil = Profile.objects.get(user=request.user)
            user_promotion = profil.promotion
            notes = Note.objects.filter(promotion = user_promotion)
    else:
        notes = None
        return redirect('accueil')
    context = {
        'notes':notes
    }
    return render(request,'note.html',context)

def TpViexs(request):
    """ Afficher touot les examen si l'utilisateur n'est pas connecter """
    if request.user.is_authenticated:
            profil = Profile.objects.get(user=request.user)
            user_promotion = profil.promotion
            tps = TP.objects.filter(promotion = user_promotion)
    else:
        tps = None
        return redirect('accueil')
    context = {
        'tps':tps
    }
    return render(request,'tp.html',context)


from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm
from .models import Profile

@login_required
def profile(request):
    # Récupérer ou créer le profil de l'utilisateur connecté
    profile, created = Profile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)

        if form.is_valid():
            form.save()
            messages.success(request, "Votre profil a été mis à jour avec succès.")
            return redirect('profile')
        else:
            # Afficher les erreurs du formulaire dans la console
            print("Formulaire invalide :", form.errors)
            messages.error(request, "Une erreur est survenue lors de la mise à jour.")
    else:
        form = ProfileForm(instance=profile)

    return render(request, 'profile.html', {'form': form, 'profile': profile})


from django.shortcuts import render
from .models import Profile, Cours, Message
    # Définir la liste des matières par défaut
def matieres_defaut():
        return [
            {"nom": "Algebre Lineaire", "heures_cours": 60, "heures_tp": 60},
            {"nom": "Physique", "heures_cours": 75, "heures_tp": 60},
            {"nom": "Analyse Math", "heures_cours": 60, "heures_tp": 60},
            {"nom": "Geometrie Analytique et plan", "heures_cours": 45, "heures_tp": 45},
            {"nom": "Calcul Numerique et Trigo", "heures_cours": 30, "heures_tp": 30},
            {"nom": "Dessin Technique", "heures_cours": 15, "heures_tp": 30},
            {"nom": "Geometrie Descriptive", "heures_cours": 30, "heures_tp": 30},
            {"nom": "Anglais", "heures_cours": 25, "heures_tp": 10},
            {"nom": "Français", "heures_cours": 30, "heures_tp": 0},
            {"nom": "Informatique", "heures_cours": 25, "heures_tp": 10},
            {"nom": "Chimie", "heures_cours": 45, "heures_tp": 45}
        ]
def matieres_defaut1():
        return [
                {"nom": "Education a la citoyenneté", "heures_cours": 30, "heures_tp": 0},
                {"nom": "Physique", "heures_cours": 75, "heures_tp": 60},
                {"nom": "Logique et expression orale et ecrit en fr", "heures_cours": 15, "heures_tp": 0},
                {"nom": "Introduction à l'infomatique", "heures_cours": 30, "heures_tp": 0},
                {"nom": "Algebre lineaire et calcul vectoriel", "heures_cours": 60, "heures_tp": 60},
                {"nom": "Analyse infinitesimale et geo diferentielle", "heures_cours": 60, "heures_tp": 60},
                {"nom": "Statique appliquée", "heures_cours": 30, "heures_tp": 30},
                {"nom": "Physique generale", "heures_cours": 90, "heures_tp": 75},
                {"nom": "Chimie genrale", "heures_cours": 45, "heures_tp": 45},
                {"nom": "Mecanique rationnelle 1", "heures_cours": 30, "heures_tp": 30},
                {"nom": "Dessin industriel", "heures_cours": 15, "heures_tp": 30}
            ]
def home(request):
    """" Affiche les informations de tous les cours si l'utilisateur n'est pas connecté """

    matieres = None 
    list_etudiant = None  # Initialiser list_etudiant en tant que None

    if request.user.is_authenticated:
        profil = Profile.objects.get(user=request.user)
        user_promotion = profil.promotion
        cours = Cours.objects.filter(promotion=user_promotion)
        list_etudiant = Profile.objects.filter(promotion=user_promotion)
        if user_promotion == 'PREPA':
             matieres = matieres_defaut()  # Initialiser les matières par défaut pour tous les utilisateurs
        else:
            matieres = matieres_defaut1()
    else:
        cours = Cours.objects.all()

    messages = Message.objects.all()  # Récupérer tous les messages

    # Contexte pour le rendu
    context = {
        'matieres': matieres,
        'cours': cours,
        'list_etudiant': list_etudiant,
        'messages_admin': messages,
    }
    
    return render(request, "accueil.html", context)


def login_view(request):
    """Permet aux utilisateurs de se connecter à leur compte existant."""
    if request.method == 'POST':
        
        form = CustomLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            print('connecter')
            if user is not None:
                login(request, user)
                messages.success(request, 'Vous êtes connecté avec succès!')
                return redirect('accueil')  # Assurez-vous que 'accueil' est défini dans vos URLs
            else:
                messages.error(request, 'Nom d\'utilisateur ou mot de passe incorrect.')
    else:
        form = CustomLoginForm()
        messages.error(request, 'Nom d\'utilisateur ou mot de passe incorrect.')
        print('sa ne mache pas ')


    return render(request,'login.html', {'form': form})


def logout_view(request):

source_polytechnique/templates/exam.html
<!DOCTYPE html>
<html lang="fr">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block page_title %}Examen | Source Academique{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/accueil.css' %}">
    <style>


/* En-tête de la page */
header {
    width: 100%;
    background-color: #fff;
    border-radius: 15px;
    padding: 20px;
    position: relative;
    overflow: hidden;
    transition: all 0.3s ease;
    box-sizing: border-box; /* Assure que le padding est inclus dans la largeur */
}

header:hover {
    transform: translateX(5px);
}

.header-frame {
    font-family: 'Grand Hotel', cursive;
    background-color: #007bb5; /* Couleur de fond */
    color: #fff; /* Couleur du texte */
    padding: 20px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-radius: 12px;
    width: 100%; /* Prendre toute la largeur */
}

/* Media Queries pour les téléphones portables */
@media (max-width: 768px) {
    header {
        width: 100%;
        padding: 10px;
        text-align: center;
    }

    .header-frame {
        flex-direction: column;
        align-items: flex-start;
        padding: 10px;
        width: 100%; /* Prendre toute la largeur */
    }

    .header-frame h1 {
        font-size: 20px;
    }

    .header-frame .logout-button {
        margin-top: 10px;
    }
}


/* Barre de navigation latérale */
.nav-frame {
    top: 10dvh;
    left: -2dvh;
    width: 100%;
    background-color: #333;
    border-radius: 12px;
    padding-top: 20px;
    box-shadow: 2px 0 5px rgba(0, 0, 0, 0.1);
    overflow-y: auto; /* Ajout pour permettre le défilement */
    position: relative; /* Permet au menu de défiler avec le contenu */
    height: 300dvh; /* Pour que la barre de navigation prenne la hauteur nécessaire */
}


.nav-frame ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
}

.nav-frame ul li {
    
    box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.3); /* Ombre portée */ 
    padding: 10px; margin: 10px;
    border-radius: 10px; /* Arrondi des coins */
    transition: background-color 0.3s;
    width: 80px;
}

.nav-frame ul li a {
    
    color: white;
    text-decoration: none;
    padding: 10px;
    display: block;
    font-weight: bold;
    
}

.nav-frame ul li:hover {
    background-color: #575757;
}
@media (max-width: 768px){
    .nav-frame {
        top: 8dvh;
        width: 800dvb;
        left: -1dvh;
    }
    .nav-frame ul {
        top: 20dvh;
        margin: 15px 0;
    }
    .nav-frame ul li {
        top: 20dvh;
        margin: 15px 0;
        width: 60px;
        transition: background-color 0.3s;
    }

    .nav-frame ul li a {
        top: 50px;
        color: white;
        text-decoration: none;
        padding: 10px;
        display: block;
        font-weight: bold;

    }
}
/* Contenu principal */
.content-frame {
    flex-grow: 1;
    top: -304dvh;
    left: -10dvh;
    min-width: auto;
    width: 100%; /* Prend en compte la largeur de la navigation et des marges */
    height: 300dvh; /* S'adapte à la hauteur du contenu */
    min-height: 100vh; /* Prend la hauteur de l'écran au minimum */
    background-color: #c2baba;
    border-radius: 20px;
    padding: 30px;
    margin-left: 170px; /* Laisse de l'espace pour la barre de navigation */
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    position: relative;
    overflow-y: auto; /* Permet le défilement si le contenu dépasse */
    box-sizing: border-box; /* Inclut padding et bordure dans le calcul de la largeur */
}

.content-frame h2{
    font-family: 'Grand Hotel', cursive;
}

/* Media Queries pour les téléphones portables */ 
@media (max-width: 768px) { 
    .content-frame { 
    left: 12dvh;
    min-width: auto;
    width: 100%; /* Prend en compte la largeur de la navigation et des marges */
    height: 300dvh; /* S'adapte à la hauteur du contenu */
    min-height: 100vh; /* Prend la hauteur de l'écran au minimum */
    background-color: #c2baba;
        padding: 15px; /* Réduit le padding */ 
        margin-left: 0; /* Enlève la marge gauche */ 
        border-radius: 20px; /* Ajuste le rayon des bordures */ 
        overflow-y:None;
        overflow-x: None;
    } 
        .content-frame h2 { font-size: 20px; /* Ajuste la taille de la police */
         }
        }
/* Style pour les tables */
.table-matiere, .table-cours, .table-etudiants {
    width: 100%;
    border-collapse: collapse;
}

.table-matiere th, .table-matiere td, .table-cours th, .table-cours td, .table-etudiants th, .table-etudiants td {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: center;
}

.table-matiere th, .table-cours th, .table-etudiants th {
    background-color: #f2f2f2;
    font-weight: bold;
}

.table-matiere tbody tr:hover, .table-cours tbody tr:hover, .table-etudiants tbody tr:hover {
    background-color: #f9f9f9;
}

/* Styles pour les images de profil */
.student-profile-img {
    width: 40px;
    height: 40px;
    border-radius: 50%;
    object-fit: cover;
    transition: transform 0.3s ease;
}

.student-profile-img:hover {
    transform: scale(1.2);
}

/* Styles pour la section des départements */
.department {
    background-color: #f5f5f5;
    border: 1px solid #ddd;
    padding: 15px;
    margin-bottom: 15px;
    border-radius: 5px;
}

/* Liste des cours proposés */
.courses ul {
    list-style-type: none;
    padding: 0;
}

.courses li {
    background-color: #e0e7ff;
    margin: 10px 0;
    padding: 10px;
    border-radius: 4px;
}

/* Conteneur général */
.container {
    position: relative;
    height: 100%;
    width: 100%;
    min-height: 100vh;
    padding: 20px;
    overflow-y: auto;
    box-sizing: border-box;
    background-color: #d4cdcd;
    display: flex;
    flex-wrap: wrap;
    gap: 5px;
}
@media (max-width: 768px) { 
    .container { 
        padding: 10px; /* Réduit le padding pour les petits écrans */ 
        gap: 2px; /* Réduit l'espace entre les éléments */ 
        height: 100%;
        width: 100%;
        overflow-y: auto;
        overflow-x: auto;
    }
}
/* Footer */
footer {
    width: 100%;
    padding: 20px;
}

footer .grid-container {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 20px;
}

footer .grid-item {
    background-color: #fff;
    padding: 20px;
    border-radius: 15px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

/* Media Queries pour les téléphones portables */
@media (max-width: 768px) {
    footer .grid-container {
        grid-template-columns: repeat(2, 1fr); /* Deux colonnes sur mobile */
    }
}

/* Cercle de connexion */
.login-circle {
    width: 60px;
    height: 60px;
    background-color: #007bb5;
    border-radius: 50%;
    display: flex;
    justify-content: center;
    align-items: center;
    overflow: hidden;
    position: absolute;
    top: 10px;
    right: 50px;
    transition: transform 0.3s ease; /* Animation fluide */
}

.login-circle img {
    width: 100%;
    height: auto;
    
}

.login-circle:hover {
    transform: scale(1.2); /* Agrandit l'image à 120% lors du survol */
}
@media (max-width: 768px) {
    .login-circle{
    width: 40px;
    height: 40px;
    right: 2%;
    top: 0%;
    }

}
    </style>
</head>
<body>

<header class="header-frame">
    <h1>{% block header_title %}Bienvenue sur Source Académique{% endblock %}</h1>
    <h4 class="login-circle">
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">
                {% if user.profile.photo %}
                    <img src="{{ user.profile.photo.url }}" alt="Photo de profil de {{ user.username }}">
                {% else %}
                    <img src="{% static 'css/profile_default.png' %}" alt="Photo de profil par défaut">
                {% endif %}
            </a>
        {% else %}
            <a href="{% url 'login' %}"><img src="{% static 'css/profile_default.png' %}" alt="Se connecter"></a>
        {% endif %}
    </h4>
</header>

<div class="container">
    <nav class="nav-frame">
        <ul>
            <li><a href="{% url 'accueil' %}">Accueil</a></li>
            <li style="background-color:#575757 ;"><a href="{% url 'exam' %}">Examens</a></li>
            <li><a href="{% url 'note' %}">Notes</a></li>
            <li><a href="{% url 'interro' %}">Interros</a></li>
            <li><a href="{% url 'tp' %}">TP</a></li>

        </ul>
    </nav>

    <main class="content-frame">
        <h2>Examens disponibles :</h2>
        <table class="table-cours">
            <thead>
                <tr>
                    <th>Nom du fichier</th>
                    <th>Promotion</th>
                    <th>Année</th>
                </tr>
            </thead>
            <tbody>
                {% for exam in exams %}
                <tr>
                    <td><a href="{{ exam.fichier.url }}">{{ exam.titre }}</a></td>
                    <td>{{ exam.promotion }}</td>
                    <td>{{ exam.date_donnee }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3">Aucun Examen trouvé</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </main>

    <footer>
        <!-- Pied de page -->
        <div class="grid-container">
            <div class="grid-item">
                <h3>Section 1</h3>
                <div class="sub-grid">
                    {% if messages %}
                        <ul>
                        {% for message in messages %}
                            <li><strong>{{ message.title }}</strong><br>{{ message.content }}<br><small>Envoyé le {{ message.created_at }}</small></li>
                        {% endfor %}
                        </ul>
                    {% else %}
                        <p>Aucun message pour l'instant.</p>
                    {% endif %}
                </div>
            </div>
            <div class="grid-item">
                <h3>Section 2</h3>
                <div class="sub-grid">
                    <div><p>Contenu de la deuxième section, sous-partie 1.</p></div>
                    <div><p>Contenu de la deuxième section, sous-partie 2.</p></div>
                </div>
            </div>
            <div class="grid-item">
                <h3>Section 3</h3>
                <div class="sub-grid">
                    <div><p>Contenu de la troisième section, sous-partie 1.</p></div>
                    <div><p>Contenu de la troisième section, sous-partie 2.</p></div>
                </div>
            </div>
            <div class="grid-item">
                <h3>Section 4</h3>
                <div class="sub-grid">
                    <div><p>Contenu de la quatrième section, sous-partie 1.</p></div>
                    <div><p>Contenu de la quatrième section, sous-partie 2.</p></div>
                </div>
            </div>
        </div>
        
    </footer>
</div>

</body>
</html>

source_polytechnique/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon Profil</title>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
</head>
<body>
    <div class="profile-container">
        <header class="header">
            <h1>{{ profile.user.username }}</h1>
            <a href="{% url 'logout' %}" class="logout-button">Déconnexion</a>
        </header>

        <div class="profile-picture-container">
            <div class="profile-picture">
                {% if profile.photo %}
                    <img src="{{ profile.photo.url }}" alt="Photo de Profil">
                {% else %}
                    <img src="{% static 'images/default_profile.png' %}" alt="Photo de Profil par défaut">
                {% endif %}
            </div>
        </div>

        <div class="profile-info">
            <h2>Informations du Profil</h2>

            <!-- Message de confirmation -->
            {% if messages %}
                {% for message in messages %}
                    <div class="message {{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}

            <form method="POST" action="{% url 'profile' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_first_name">Prénom:</label>
                    {{ form.first_name }}
                </div>
                <div class="form-group">
                    <label for="id_last_name">Nom:</label>
                    {{ form.last_name }}
                </div>
                <div class="form-group">
                    <label for="id_photo">Photo de Profil:</label>
                    {{ form.photo }}
                </div>
                <div class="form-group">
                    <label for="id_promotion">Promotion:</label>
                    {{ form.promotion }}
                </div>
                <div class="form-group">
                    <label for="id_numero_whatsapp">Numéro WhatsApp:</label>
                    {{ form.numero_whatsapp }}
                </div>
                <button type="submit" class="update-button">Mettre à jour</button>
            </form>

            <!-- Lien pour revenir à l'accueil -->
            <div class="home-link">
                <a href="{% url 'accueil' %}" class="home-button">Retour à l'accueil</a>
            </div>
        </div>
    </div>
</body>
</html>